### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/ssconfig/client.json'

### ISSUE THREAD

**Issue by mashirozx** [HMBSbige/shadowsocksr-docker#2]
```
IPv6 not support

Traceback (most recent call last):

  File "local.py", line 81, in <module>

    main()

  File "local.py", line 43, in main

    config = shell.get_config(True)

  File "/~/shadowsocksr-manyuser/shadowsocks/../shadowsocks/shell.py", line 168, in get_config

    with open(config_path, 'rb') as f:

IOError: [Errno 2] No such file or directory: '/ssconfig/client.json'
```

**Comment by HMBSbige** [comment]
配置文件启动要有配置文件啊，这不写着你没设置吗？

仔细看 example，不会 Docker，建议先自学
